name: 'Tag an NPM release'
description: 'Tags a specific npm version to a specific channel.'

inputs:
  channel:
    description: 'NPM Channel tag'
    required: true
  version:
    description: 'version'
    required: true
  dry-run:
    description: 'Whether to run in dry-run mode.'
    required: true
  github-token:
    description: 'The GitHub token for creating the release.'
    required: true
  wombat-token-core:
    description: 'The npm token for the wombat @thacio/auditaria-cli-core'
    required: true
  wombat-token-cli:
    description: 'The npm token for wombat @thacio/auditaria-cli'
    required: true
  wombat-token-a2a-server:
    description: 'The npm token for the @google/gemini-cli-a2a-server package.'
    required: true
  cli-package-name:
    description: 'The name of the cli package.'
    required: true
  core-package-name:
    description: 'The name of the core package.'
    required: true
  a2a-package-name:
    description: 'The name of the a2a package.'
    required: true
  ref:
    description: 'The branch, tag, or SHA to release from.'
    required: false
    type: 'string'
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: '📝 Print Inputs'
      shell: 'bash'
      env:
        JSON_INPUTS: '${{ toJSON(inputs) }}'
      run: 'echo "$JSON_INPUTS"'

    - name: 'Checkout'
      uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # ratchet:actions/checkout@v4
      with:
        ref: '${{ github.event.inputs.ref }}'
        fetch-depth: 0

    - name: 'Setup Node.js'
      uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020'
      with:
        node-version-file: '.nvmrc'

    - name: 'configure .npmrc'
      uses: './.github/actions/setup-npmrc'
      with:
        github-token: '${{ inputs.github-token }}'

    - name: 'Get core Token'
      uses: './.github/actions/npm-auth-token'
      id: 'core-token'
      with:
        package-name: '${{ inputs.core-package-name }}'
        github-token: '${{ inputs.github-token }}'
        wombat-token-core: '${{ inputs.wombat-token-core }}'
        wombat-token-cli: '${{ inputs.wombat-token-cli }}'
        wombat-token-a2a-server: '${{ inputs.wombat-token-a2a-server }}'

    - name: 'Change tag for CORE'
      if: |-
        ${{ inputs.dry-run != 'true' }}
      env:
        NODE_AUTH_TOKEN: '${{ steps.core-token.outputs.auth-token }}'
      shell: 'bash'
      run: |
        npm dist-tag add ${{ inputs.core-package-name }}@${{ inputs.version }} ${{ inputs.channel }}

    - name: 'Get cli Token'
      uses: './.github/actions/npm-auth-token'
      id: 'cli-token'
      with:
        package-name: '${{ inputs.cli-package-name }}'
        github-token: '${{ inputs.github-token }}'
        wombat-token-core: '${{ inputs.wombat-token-core }}'
        wombat-token-cli: '${{ inputs.wombat-token-cli }}'
        wombat-token-a2a-server: '${{ inputs.wombat-token-a2a-server }}'

    - name: 'Change tag for CLI'
      if: |-
        ${{ inputs.dry-run != 'true' }}
      env:
        NODE_AUTH_TOKEN: '${{ steps.cli-token.outputs.auth-token }}'
      shell: 'bash'
      run: |
        npm dist-tag add ${{ inputs.cli-package-name }}@${{ inputs.version }} ${{ inputs.channel }}

    - name: 'Change tag for @google/gemini-cli-a2a-server'
      if: |-
        ${{ inputs.dry-run == 'false' }}
      env:
        NODE_AUTH_TOKEN: '${{ inputs.wombat-token-a2a-server }}'
      shell: 'bash'
      run: |
        npm dist-tag add @google/gemini-cli-a2a-server@${{ inputs.version }} ${{ inputs.channel }}

    - name: 'Log dry run'
      if: |-
        ${{ inputs.dry-run == 'true' }}
      shell: 'bash'
      run: |
        echo "Dry run: Would have added tag '${{ inputs.channel }}' to version '${{ inputs.version }}' for @google/gemini-cli and @google/gemini-cli-core."
