/**
 * AUDITARIA_BROWSER_AGENT_FEATURE: Browser Agent Tool
 *
 * This tool allows Auditaria to use a browser automation agent (browser-use)
 * to perform web tasks. It bridges Auditaria's OAuth credentials to the
 * Python browser-use library.
 *
 * Architecture:
 * - Python (browser-use): Dumb executor, returns raw data (base64 screenshots, step info)
 * - TypeScript (this file): Smart orchestrator, creates sessions, saves files, structures output
 *
 * This separation allows Python to be shipped as a binary while Auditaria retains
 * full control over session management and output formatting.
 */

import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Config } from '../config/config.js';
import { Storage } from '../config/storage.js';
import { AuthType } from '../core/contentGenerator.js';
import { ToolErrorType } from './tool-error.js';
import type { ToolInvocation, ToolResult } from './tools.js';
import { BaseDeclarativeTool, BaseToolInvocation, Kind } from './tools.js';
import { BROWSER_AGENT_TOOL_NAME } from './tool-names.js';
import type { MessageBus } from '../confirmation-bus/message-bus.js';

export interface BrowserAgentToolParams {
  task: string;
  headless?: boolean;
  model?: string;
  /** Screenshot capture mode: 'none', 'all', or 'final'. Default: 'none' */
  screenshotMode?: 'none' | 'all' | 'final';
  /** Custom session folder path. Default: browser-sessions/<auto-generated>/ */
  sessionFolder?: string;
  /** Maximum steps before stopping. Default: 50 */
  maxSteps?: number;
}

/** Represents a single step in the browser agent execution */
export interface BrowserAgentStep {
  step: number;
  timestamp: string;
  url: string | null;
  title: string | null;
  goal: string | null;
  action: string | null;
  evaluation: string | null;
  screenshotPath: string | null;
}

/** Structured result returned by the browser agent */
export interface BrowserAgentResult {
  success: boolean;
  result: string | null;
  sessionPath: string | null;
  steps: BrowserAgentStep[];
  totalSteps: number;
  durationMs: number;
  stopped: boolean;
  stopReason: string | null;
}

interface OAuthCredentials {
  access_token?: string;
  refresh_token?: string;
  client_id?: string;
  client_secret?: string;
  token_uri?: string;
  scopes?: string[];
}

export class BrowserAgentToolInvocation extends BaseToolInvocation<
  BrowserAgentToolParams,
  ToolResult
> {
  constructor(
    private readonly config: Config,
    params: BrowserAgentToolParams,
    messageBus?: MessageBus,
  ) {
    super(params, messageBus);
  }

  getDescription(): string {
    const headless = this.params.headless !== false ? 'headless' : 'visible';
    return `Browser agent task (${headless}): ${this.params.task.substring(0, 100)}${this.params.task.length > 100 ? '...' : ''}`;
  }

  async execute(
    signal: AbortSignal,
    updateOutput?: (output: string) => void,
  ): Promise<ToolResult> {
    const startTime = Date.now();

    if (signal.aborted) {
      return {
        llmContent: 'Browser agent task was cancelled before it could start.',
        returnDisplay: 'Task cancelled.',
      };
    }

    // Find the browser-use directory relative to project root
    const projectRoot = this.config.getTargetDir();
    const browserUsePath = path.join(projectRoot, 'browser-use');
    const agentScriptPath = path.join(browserUsePath, 'auditaria_agent.py');

    // Check if the agent script exists
    if (!fs.existsSync(agentScriptPath)) {
      return {
        llmContent: `Browser agent script not found at ${agentScriptPath}. Please ensure browser-use is set up correctly.`,
        returnDisplay: 'Browser agent not available.',
        error: {
          message: 'Browser agent script not found',
          type: ToolErrorType.EXECUTION_FAILED,
        },
      };
    }

    // Get credentials
    const credentials = await this.getCredentials();
    if (!credentials) {
      return {
        llmContent:
          'No valid credentials found. Please authenticate with Google first using OAuth or provide an API key.',
        returnDisplay: 'No credentials available.',
        error: {
          message: 'No credentials found',
          type: ToolErrorType.EXECUTION_FAILED,
        },
      };
    }

    // Determine screenshot mode
    const screenshotMode = this.params.screenshotMode || 'none';
    const captureScreenshots = screenshotMode !== 'none';

    // Create session folder if capturing screenshots
    let sessionPath: string | null = null;
    if (captureScreenshots) {
      sessionPath = this.createSessionFolder(projectRoot);
    }

    // Spawn the process - pass all data via stdin to avoid shell escaping issues
    const env = {
      ...process.env,
      PYTHONUTF8: '1', // Handle Unicode on Windows
    };

    // Build input payload to pass via stdin (avoids all shell escaping issues)
    const inputPayload = {
      task: this.params.task,
      headless: this.params.headless !== false,
      model: this.params.model || 'gemini-2.0-flash',
      credentials: credentials.type === 'oauth' ? credentials.data : null,
      api_key: credentials.type === 'api_key' ? credentials.data : null,
      include_screenshots: captureScreenshots,
      max_steps: this.params.maxSteps || 50,
    };

    // Spawn with minimal args - data comes via stdin
    const spawnArgs = ['run', 'python', agentScriptPath, '--stdin'];
    const child = spawn('uv', spawnArgs, {
      cwd: browserUsePath,
      env,
      shell: process.platform === 'win32', // Shell needed on Windows to find uv
      windowsHide: true,
    });

    // Send input via stdin (with newline - Python reads first line as config)
    // Keep stdin open for subsequent commands (like STOP)
    child.stdin.write(JSON.stringify(inputPayload) + '\n');

    let stdout = '';
    let stderr = '';
    let lineBuffer = '';
    let finalResult: string | null = null;
    let wasStopped = false;
    let stopReason: string | null = null;
    const steps: BrowserAgentStep[] = [];

    // Handle stdout - parse JSON lines for progress
    child.stdout.on('data', (data: Buffer) => {
      const text = data.toString();
      stdout += text;
      lineBuffer += text;

      // Process complete JSON lines
      const lines = lineBuffer.split('\n');
      lineBuffer = lines.pop() || ''; // Keep incomplete line in buffer

      for (const line of lines) {
        if (!line.trim()) continue;

        try {
          const event = JSON.parse(line) as {
            type: string;
            step?: number;
            goal?: string;
            eval?: string;
            result?: string;
            total_steps?: number;
            message?: string;
            url?: string;
            title?: string;
            timestamp?: string;
            actions?: Array<{ [key: string]: unknown }>;
            screenshot?: string;
            thumbnail?: string;
            partial_result?: string;
          };

          // Update progress based on event type
          switch (event.type) {
            case 'start':
              if (updateOutput) updateOutput('Browser agent starting...');
              break;

            case 'step': {
              const stepNum = event.step || steps.length + 1;
              const stepInfo = event.goal
                ? `Step ${stepNum}: ${event.goal}`
                : `Step ${stepNum}`;
              if (updateOutput) updateOutput(stepInfo);

              // Extract action description from actions array
              let actionDesc: string | null = null;
              if (event.actions && event.actions.length > 0) {
                const actionKeys = Object.keys(event.actions[0]);
                actionDesc = actionKeys[0] || null;
              }

              // Save screenshot if available
              let screenshotPath: string | null = null;
              if (sessionPath && event.screenshot) {
                const shouldSave =
                  screenshotMode === 'all' ||
                  (screenshotMode === 'final' && event.actions?.some((a) => 'done' in a));
                if (shouldSave) {
                  screenshotPath = this.saveScreenshot(
                    sessionPath,
                    stepNum,
                    event.screenshot,
                  );
                }
              }

              // Record step
              steps.push({
                step: stepNum,
                timestamp: event.timestamp || new Date().toISOString(),
                url: event.url || null,
                title: event.title || null,
                goal: event.goal || null,
                action: actionDesc,
                evaluation: event.eval || null,
                screenshotPath,
              });
              break;
            }

            case 'done':
              finalResult = event.result || null;
              if (updateOutput) updateOutput(`Completed in ${steps.length} steps`);
              break;

            case 'stopping':
              if (updateOutput) updateOutput('Stopping...');
              break;

            case 'stopped':
              wasStopped = true;
              stopReason = event.message || 'User requested stop';
              finalResult = event.partial_result || null;
              if (updateOutput) updateOutput(`Stopped after ${steps.length} steps`);
              break;

            case 'error':
              if (updateOutput) updateOutput(`Error: ${event.message}`);
              break;

            case 'info':
              // Don't show info messages in progress
              break;
          }
        } catch {
          // Not a JSON line, might be browser-use's own logging
          // Ignore non-JSON output
        }
      }
    });

    // Handle stderr
    child.stderr.on('data', (data: Buffer) => {
      stderr += data.toString();
    });

    // Handle abort - send STOP command for graceful shutdown
    const abortHandler = () => {
      // Try graceful stop first by sending STOP command via stdin
      try {
        if (!child.stdin.destroyed) {
          child.stdin.write('STOP\n');
          child.stdin.end();
        }
      } catch {
        // Stdin might already be closed, ignore
      }

      // Give the agent a moment to stop gracefully, then force kill
      setTimeout(() => {
        if (!child.killed) {
          child.kill('SIGTERM');
        }
      }, 2000);
    };
    signal.addEventListener('abort', abortHandler, { once: true });

    // Wait for completion
    const exitCode = await new Promise<number | null>((resolve) => {
      child.on('close', (code) => {
        signal.removeEventListener('abort', abortHandler);
        // Close stdin if still open
        if (!child.stdin.destroyed) {
          try {
            child.stdin.end();
          } catch {
            // Ignore errors
          }
        }
        resolve(code);
      });
      child.on('error', () => {
        signal.removeEventListener('abort', abortHandler);
        resolve(null);
      });
    });

    const durationMs = Date.now() - startTime;

    // Build structured result
    const agentResult: BrowserAgentResult = {
      success: exitCode === 0 && !wasStopped && !signal.aborted,
      result: finalResult || this.extractFinalResult(stdout),
      sessionPath,
      steps,
      totalSteps: steps.length,
      durationMs,
      stopped: wasStopped || signal.aborted,
      stopReason: wasStopped ? stopReason : signal.aborted ? 'User cancelled' : null,
    };

    // Save session metadata if we have a session folder
    if (sessionPath) {
      this.saveSessionMetadata(sessionPath, agentResult);
    }

    // Format output for LLM
    const llmContent = this.formatLLMOutput(agentResult);

    // Handle error cases
    if (exitCode !== 0 && !wasStopped && !signal.aborted) {
      const errorMessage = stderr || 'Unknown error';
      return {
        llmContent: `Browser agent task failed with exit code ${exitCode}.\nError: ${errorMessage}\n\n${llmContent}`,
        returnDisplay: `Task failed: ${errorMessage}`,
        error: {
          message: errorMessage,
          type: ToolErrorType.EXECUTION_FAILED,
        },
      };
    }

    return {
      llmContent,
      returnDisplay: agentResult.result || (agentResult.stopped ? 'Task stopped.' : 'Task completed.'),
    };
  }

  /**
   * Create a session folder for storing screenshots and metadata
   */
  private createSessionFolder(projectRoot: string): string {
    const baseFolder = this.params.sessionFolder || 'browser-sessions';
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const taskHash = this.hashString(this.params.task).slice(0, 8);
    const sessionName = `${timestamp}_${taskHash}`;
    const sessionPath = path.join(projectRoot, baseFolder, sessionName);

    fs.mkdirSync(sessionPath, { recursive: true });
    return sessionPath;
  }

  /**
   * Save a screenshot to the session folder
   */
  private saveScreenshot(sessionPath: string, stepNum: number, base64Data: string): string {
    const filename = `step-${String(stepNum).padStart(2, '0')}.png`;
    const filePath = path.join(sessionPath, filename);

    try {
      const buffer = Buffer.from(base64Data, 'base64');
      fs.writeFileSync(filePath, buffer);
      return filePath;
    } catch {
      return ''; // Return empty string if save failed
    }
  }

  /**
   * Save session metadata as JSON
   */
  private saveSessionMetadata(sessionPath: string, result: BrowserAgentResult): void {
    const metadataPath = path.join(sessionPath, 'session.json');
    const metadata = {
      task: this.params.task,
      createdAt: new Date().toISOString(),
      ...result,
    };

    try {
      fs.writeFileSync(metadataPath, JSON.stringify(metadata, null, 2));
    } catch {
      // Ignore save errors
    }
  }

  /**
   * Format the result for LLM consumption
   */
  private formatLLMOutput(result: BrowserAgentResult): string {
    const lines: string[] = [];

    // Header
    if (result.stopped) {
      lines.push(`Browser agent was stopped: ${result.stopReason}`);
    } else if (result.success) {
      lines.push(`Browser agent completed successfully.`);
    } else {
      lines.push(`Browser agent encountered an issue.`);
    }

    lines.push(`Duration: ${Math.round(result.durationMs / 1000)}s | Steps: ${result.totalSteps}`);
    lines.push('');

    // Task
    lines.push(`**Task:** ${this.params.task}`);
    lines.push('');

    // Result
    if (result.result) {
      lines.push(`**Result:** ${result.result}`);
      lines.push('');
    }

    // Session folder
    if (result.sessionPath) {
      lines.push(`**Session folder:** ${result.sessionPath}`);
      lines.push('');
    }

    // Steps summary
    if (result.steps.length > 0) {
      lines.push('**Steps:**');
      for (const step of result.steps) {
        const screenshot = step.screenshotPath ? ` [📷 ${path.basename(step.screenshotPath)}]` : '';
        lines.push(`${step.step}. ${step.goal || 'Action'}${screenshot}`);
        if (step.url) {
          lines.push(`   URL: ${step.url}`);
        }
      }
    }

    return lines.join('\n');
  }

  /**
   * Simple hash function for generating session folder names
   */
  private hashString(str: string): string {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(16);
  }

  private async getCredentials(): Promise<{
    type: 'oauth' | 'api_key';
    data: string | OAuthCredentials;
  } | null> {
    // Get the CLI's current auth type to stay in sync
    const contentGeneratorConfig = this.config.getContentGeneratorConfig();
    const authType = contentGeneratorConfig?.authType;

    // If CLI is using API key (Gemini or Vertex AI), use the same API key
    if (
      authType === AuthType.USE_GEMINI ||
      authType === AuthType.USE_VERTEX_AI
    ) {
      const apiKey =
        contentGeneratorConfig?.apiKey ||
        process.env['GEMINI_API_KEY'] ||
        process.env['GOOGLE_API_KEY'];
      if (apiKey) {
        return { type: 'api_key', data: apiKey };
      }
    }

    // If CLI is using OAuth (LOGIN_WITH_GOOGLE), use OAuth credentials
    if (authType === AuthType.LOGIN_WITH_GOOGLE) {
      const oauthPath = Storage.getOAuthCredsPath();
      if (fs.existsSync(oauthPath)) {
        try {
          const content = fs.readFileSync(oauthPath, 'utf-8');
          const creds = JSON.parse(content) as OAuthCredentials;
          if (creds.access_token) {
            return { type: 'oauth', data: creds };
          }
        } catch {
          // OAuth file couldn't be read
        }
      }
    }

    // Fallback: try OAuth credentials first, then API key
    // (for cases where authType is not set or is COMPUTE_ADC)
    const oauthPath = Storage.getOAuthCredsPath();
    if (fs.existsSync(oauthPath)) {
      try {
        const content = fs.readFileSync(oauthPath, 'utf-8');
        const creds = JSON.parse(content) as OAuthCredentials;
        if (creds.access_token) {
          return { type: 'oauth', data: creds };
        }
      } catch {
        // Continue to API key fallback
      }
    }

    // Final fallback: environment API keys
    const apiKey =
      process.env['GEMINI_API_KEY'] || process.env['GOOGLE_API_KEY'];
    if (apiKey) {
      return { type: 'api_key', data: apiKey };
    }

    return null;
  }

  private extractFinalResult(output: string): string {
    // Look for "Final result:" in the output
    const match = output.match(/Final result:\s*(.+?)(?:\n|$)/s);
    if (match) {
      return match[1].trim();
    }

    // Look for the last non-empty line that contains useful content
    const lines = output.split('\n').filter((line) => line.trim());
    for (let i = lines.length - 1; i >= 0; i--) {
      const line = lines[i].trim();
      // Skip common noise lines
      if (
        line.startsWith('===') ||
        line.startsWith('Starting') ||
        line.startsWith('Using')
      ) {
        continue;
      }
      if (line.length > 10) {
        return line;
      }
    }

    return '';
  }
}

export class BrowserAgentTool extends BaseDeclarativeTool<
  BrowserAgentToolParams,
  ToolResult
> {
  static readonly Name = BROWSER_AGENT_TOOL_NAME;

  constructor(
    private readonly config: Config,
    messageBus?: MessageBus,
  ) {
    super(
      BrowserAgentTool.Name,
      'Browser Agent',
      `Use a browser automation agent to perform web tasks. The agent can navigate websites, interact with elements, fill forms, extract information, and more.

This tool launches a browser (headless by default) and uses an AI agent to complete the given task autonomously.

Use cases:
- Search for information on websites
- Navigate to specific pages and extract data
- Fill out forms and interact with web applications
- Take screenshots of web pages
- Perform multi-step web workflows

The agent uses your authenticated Google credentials to access web content.

IMPORTANT: Only use this tool when the user explicitly asks you to use a browser or needs real-time web interaction. For simple information retrieval, prefer the google_web_search tool.`,
      Kind.Execute,
      {
        type: 'object',
        properties: {
          task: {
            type: 'string',
            description:
              'The task for the browser agent to perform. Be specific and detailed about what you want the agent to do.',
          },
          headless: {
            type: 'boolean',
            description:
              'Whether to run the browser in headless mode (invisible). Defaults to true. Set to false to show the browser window.',
          },
          model: {
            type: 'string',
            description:
              'The model to use for the browser agent. Defaults to gemini-2.0-flash.',
          },
          screenshotMode: {
            type: 'string',
            enum: ['none', 'all', 'final'],
            description:
              'Screenshot capture mode. "none": no screenshots (default). "all": capture at every step. "final": capture only the final step. Screenshots are saved to the session folder.',
          },
          sessionFolder: {
            type: 'string',
            description:
              'Custom folder path for saving session data (screenshots, metadata). Defaults to "browser-sessions/<auto-generated>/".',
          },
          maxSteps: {
            type: 'number',
            description:
              'Maximum number of steps before the agent stops. Defaults to 50. Use to prevent runaway loops.',
          },
        },
        required: ['task'],
      },
      false, // isOutputMarkdown
      true, // canUpdateOutput
      messageBus,
    );
  }

  protected override validateToolParamValues(
    params: BrowserAgentToolParams,
  ): string | null {
    if (!params.task || !params.task.trim()) {
      return 'Task cannot be empty.';
    }
    return null;
  }

  protected createInvocation(
    params: BrowserAgentToolParams,
    messageBus?: MessageBus,
  ): ToolInvocation<BrowserAgentToolParams, ToolResult> {
    return new BrowserAgentToolInvocation(this.config, params, messageBus);
  }
}
